name: test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          node-version: '16.13.1'
      - name: test
        uses: ArtiomTr/jest-coverage-report-action@v2
